namespace ActiveMesa.FSharper.Feature.Services.FSharp.CodeCompletion.Infrastructure

open JetBrains.ReSharper.Feature.Services.CodeCompletion.Impl

type FSharpCodeCompletionContextProvider =
  CodeCompletionContextProviderWithReparse